package com.xiaoming.springbootlearning.controller;

import com.xiaoming.springbootlearning.entities.MyUser;
import com.xiaoming.springbootlearning.entities.MyUserRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

/**
 * @author Xiaoming.
 * Created on 2018/11/22 11:40.
 * Description :
 */
@RestController
public class Sign {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private MyUserRepository userRepository;

    @PostMapping(path = "/signup")
    @RequestMapping(path = "/signup")
    public MyUser signUp(@RequestParam(value = "username") String name, @RequestParam(value = "password") String psw, @RequestParam(value = "email") String email) {
        MyUser u = new MyUser();
        u.setNickName(name);
        u.setPassword(psw);
        u.setEmail(email);
        userRepository.save(u);

        return u;
    }

    @PostMapping(path = "/signin")
    @RequestMapping(path = "/signin")
    public ResponseEntity<MyUser> signIn(@RequestParam(value = "username") String name, @RequestParam(value = "password") String psw) {
        MyUser result = userRepository.findMyUserByNickNameAndPassword(name, psw);
        HttpStatus status = result == null ? HttpStatus.NOT_FOUND : HttpStatus.OK;

        //System.out.println(name + " " + psw);

        return new ResponseEntity<MyUser>(result, status);
    }

    @GetMapping(path = "/all")
    public @ResponseBody
    Iterable<MyUser> getAllUsers() {
        // This returns a JSON or XML with the users
        return userRepository.findAll();
    }
}
